// Demo data for CivicAI — used when database is unavailable
// Replace with real database calls when DB is connected

export const DEMO_STATS = {
  total: 12482,
  resolved: 8920,
  inProgress: 2410,
  pending: 1152,
  critical: 184,
  resolutionRate: 71.5,
  avgResolutionHours: 36,
  citizensSatisfied: 89,
}

export const DEMO_COMPLAINTS = [
  {
    id: 'demo-1',
    civicId: 'CIV-10271',
    title: 'Drainage Overflow Near Residential Area',
    description: 'Sewage and drainage water overflowing on Main Road near the residential apartments. Very bad smell and health hazard for children.',
    category: 'DRAINAGE',
    categoryDisplay: 'Drainage Blockage',
    severity: 'CRITICAL',
    priority: 'CRITICAL',
    priorityScore: 94,
    status: 'IN_PROGRESS',
    ward: '12',
    municipality: 'Demo Municipal Corporation',
    department: 'Drainage Department',
    address: 'Main Road, Kattur, Ward 12',
    latitude: 10.7905,
    longitude: 78.7047,
    supportCount: 17,
    slaHours: 24,
    slaBreached: true,
    escalationLevel: 'LEVEL1',
    aiConfidence: 0.97,
    language: 'english',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Arjun Kumar', email: 'citizen@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-2',
    civicId: 'CIV-10272',
    title: 'Large Pothole Near Government School',
    description: 'There is a huge pothole near the school on Anna Salai. Many bikes are almost falling. Very dangerous for school children.',
    category: 'POTHOLE',
    categoryDisplay: 'Pothole / Road Pit',
    severity: 'HIGH',
    priority: 'HIGH',
    priorityScore: 88,
    status: 'ASSIGNED',
    ward: '12',
    municipality: 'Demo Municipal Corporation',
    department: 'Roads Department',
    address: 'Anna Salai, Near Govt School, Ward 12',
    latitude: 10.7920,
    longitude: 78.7060,
    supportCount: 14,
    slaHours: 48,
    slaBreached: false,
    escalationLevel: 'NONE',
    aiConfidence: 0.95,
    language: 'english',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Arjun Kumar', email: 'citizen@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-3',
    civicId: 'CIV-10273',
    title: 'Street Light Not Working',
    description: 'Street light near bus stop not working for past 5 days. Area is very dark at night, unsafe.',
    category: 'STREET_LIGHT',
    categoryDisplay: 'Street Light Issue',
    severity: 'MEDIUM',
    priority: 'MEDIUM',
    priorityScore: 62,
    status: 'RESOLVED',
    ward: '8',
    municipality: 'Demo Municipal Corporation',
    department: 'Street Light Department',
    address: 'Bus Stop Road, Ward 8',
    latitude: 10.7870,
    longitude: 78.7030,
    supportCount: 7,
    slaHours: 72,
    slaBreached: false,
    escalationLevel: 'NONE',
    aiConfidence: 0.88,
    language: 'english',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    resolutionNote: 'Street light bulb replaced. Tested and working.',
    citizen: { name: 'Arjun Kumar', email: 'citizen@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-4',
    civicId: 'CIV-10274',
    title: 'Garbage Accumulation at Street Corner',
    description: 'Huge pile of garbage accumulated at the corner of Market Street. No collection for 4 days.',
    category: 'GARBAGE',
    categoryDisplay: 'Garbage Accumulation',
    severity: 'HIGH',
    priority: 'HIGH',
    priorityScore: 78,
    status: 'SUBMITTED',
    ward: '14',
    municipality: 'Demo Municipal Corporation',
    department: 'Sanitation Department',
    address: 'Market Street Corner, Ward 14',
    latitude: 10.7945,
    longitude: 78.7080,
    supportCount: 23,
    slaHours: 24,
    slaBreached: true,
    escalationLevel: 'NONE',
    aiConfidence: 0.91,
    language: 'english',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Priya Devi', email: 'priya@demo.com' },
    officer: null,
  },
  {
    id: 'demo-5',
    civicId: 'CIV-10275',
    title: 'Water Pipeline Leakage on NH Road',
    description: 'Water leaking from underground pipeline on NH road. Road is waterlogged and creating traffic problems.',
    category: 'WATER_LEAKAGE',
    categoryDisplay: 'Water Leakage / Pipe Burst',
    severity: 'CRITICAL',
    priority: 'CRITICAL',
    priorityScore: 96,
    status: 'IN_PROGRESS',
    ward: '5',
    municipality: 'Demo Municipal Corporation',
    department: 'Water Department',
    address: 'NH Bypass Road, Ward 5',
    latitude: 10.7855,
    longitude: 78.7015,
    supportCount: 31,
    slaHours: 12,
    slaBreached: true,
    escalationLevel: 'LEVEL1',
    aiConfidence: 0.93,
    language: 'english',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Priya Devi', email: 'priya@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-6',
    civicId: 'CIV-10276',
    title: 'Sewage Overflow Blocking School Road',
    description: 'Sewage overflow completely blocking the road near elementary school. Parents and children unable to access school.',
    category: 'SEWAGE',
    categoryDisplay: 'Sewage Overflow',
    severity: 'CRITICAL',
    priority: 'CRITICAL',
    priorityScore: 98,
    status: 'ESCALATED',
    ward: '3',
    municipality: 'Demo Municipal Corporation',
    department: 'Drainage Department',
    address: 'School Road, Ward 3',
    latitude: 10.7835,
    longitude: 78.7000,
    supportCount: 42,
    slaHours: 24,
    slaBreached: true,
    escalationLevel: 'LEVEL2',
    aiConfidence: 0.97,
    language: 'english',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Priya Devi', email: 'priya@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-7',
    civicId: 'CIV-10277',
    title: 'Road Surface Completely Damaged After Rain',
    description: 'Heavy rain has completely damaged the road surface. Multiple potholes and loose gravel. Accidents happening daily.',
    category: 'ROAD_DAMAGE',
    categoryDisplay: 'Road Surface Damage',
    severity: 'HIGH',
    priority: 'HIGH',
    priorityScore: 82,
    status: 'ASSIGNED',
    ward: '7',
    municipality: 'Demo Municipal Corporation',
    department: 'Roads Department',
    address: 'Colony Main Road, Ward 7',
    latitude: 10.7890,
    longitude: 78.7065,
    supportCount: 19,
    slaHours: 72,
    slaBreached: false,
    escalationLevel: 'NONE',
    aiConfidence: 0.89,
    language: 'english',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Arjun Kumar', email: 'citizen@demo.com' },
    officer: { name: 'Rajesh Murugan' },
  },
  {
    id: 'demo-8',
    civicId: 'CIV-10278',
    title: 'Illegal Dumping of Construction Waste',
    description: 'Someone is illegally dumping construction debris on the roadside. Blocking footpath and causing pollution.',
    category: 'ILLEGAL_DUMPING',
    categoryDisplay: 'Illegal Dumping',
    severity: 'MEDIUM',
    priority: 'MEDIUM',
    priorityScore: 55,
    status: 'SUBMITTED',
    ward: '9',
    municipality: 'Demo Municipal Corporation',
    department: 'Sanitation Department',
    address: 'Industrial Area Road, Ward 9',
    latitude: 10.7960,
    longitude: 78.7090,
    supportCount: 5,
    slaHours: 48,
    slaBreached: false,
    escalationLevel: 'NONE',
    aiConfidence: 0.84,
    language: 'english',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    citizen: { name: 'Priya Devi', email: 'priya@demo.com' },
    officer: null,
  },
]

export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'STATUS_CHANGE',
    title: 'Complaint Assigned',
    message: 'Your complaint CIV-10271 has been assigned to the Drainage Department.',
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    complaintId: 'demo-1',
  },
  {
    id: 'notif-2',
    type: 'STATUS_CHANGE',
    title: 'Work In Progress',
    message: 'Field team has been dispatched for complaint CIV-10271.',
    read: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    complaintId: 'demo-1',
  },
  {
    id: 'notif-3',
    type: 'ASSIGNED',
    title: 'Complaint Assigned',
    message: 'Your pothole complaint CIV-10272 has been assigned to Roads Department.',
    read: true,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    complaintId: 'demo-2',
  },
  {
    id: 'notif-4',
    type: 'SLA_BREACH',
    title: '⚠️ SLA Breached',
    message: 'Complaint CIV-10274 has exceeded its SLA deadline and has been escalated.',
    read: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    complaintId: 'demo-4',
  },
]

export const DEMO_ANALYTICS = {
  byCategory: [
    { name: 'Pothole', value: 2840, color: '#f59e0b' },
    { name: 'Drainage', value: 2210, color: '#3b82f6' },
    { name: 'Garbage', value: 1980, color: '#10b981' },
    { name: 'Street Light', value: 1540, color: '#8b5cf6' },
    { name: 'Water Leakage', value: 1320, color: '#ef4444' },
    { name: 'Road Damage', value: 1190, color: '#f97316' },
    { name: 'Sewage', value: 890, color: '#6366f1' },
    { name: 'Other', value: 512, color: '#6b7280' },
  ],
  byStatus: [
    { name: 'Resolved', value: 8920, color: '#10b981' },
    { name: 'In Progress', value: 2410, color: '#3b82f6' },
    { name: 'Submitted', value: 752, color: '#f59e0b' },
    { name: 'Assigned', value: 400, color: '#8b5cf6' },
    { name: 'Escalated', value: 184, color: '#ef4444' },
  ],
  weekly: [
    { day: 'Mon', submitted: 42, resolved: 38 },
    { day: 'Tue', submitted: 38, resolved: 44 },
    { day: 'Wed', submitted: 55, resolved: 41 },
    { day: 'Thu', submitted: 47, resolved: 52 },
    { day: 'Fri', submitted: 61, resolved: 48 },
    { day: 'Sat', submitted: 33, resolved: 39 },
    { day: 'Sun', submitted: 28, resolved: 31 },
  ],
  monthly: [
    { month: 'Jan', complaints: 380, resolved: 290 },
    { month: 'Feb', complaints: 420, resolved: 350 },
    { month: 'Mar', complaints: 510, resolved: 420 },
    { month: 'Apr', complaints: 480, resolved: 410 },
    { month: 'May', complaints: 560, resolved: 480 },
    { month: 'Jun', complaints: 620, resolved: 520 },
    { month: 'Jul', complaints: 590, resolved: 510 },
    { month: 'Aug', complaints: 640, resolved: 580 },
  ],
}

export const DEMO_USERS = {
  citizen: {
    id: 'demo-citizen',
    name: 'Arjun Kumar',
    email: 'citizen@demo.com',
    role: 'CITIZEN',
    phone: '9876543210',
    ward: '12',
  },
  officer: {
    id: 'demo-officer',
    name: 'Rajesh Murugan',
    email: 'officer@demo.com',
    role: 'OFFICER',
    phone: '9876543212',
    ward: '12',
  },
}
